import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { testBase } from '../../scripts/test-base.js'
import { createEntry } from '../../src/utils/entry.js'

async function start(page) {
  await page.goto('./')
  await expect(page.getByRole('heading', { name: '오늘은 어떤 차를 마셨나요?' })).toBeVisible()
}
async function create(page, name, { rating = 0, category = '', feeling = '', tags = '' } = {}) {
  await page.getByRole('navigation').getByRole('link', { name: '새 기록', exact: true }).click()
  await page.getByLabel('차 이름 *').fill(name)
  if (category) await page.getByLabel('차 종류', { exact: true }).selectOption(category)
  if (rating) await page.getByRole('button', { name: `${rating}점`, exact: true }).click()
  if (feeling) await page.getByLabel('차를 마시면서 느낀 점').fill(feeling)
  if (tags) await page.getByLabel('태그', { exact: true }).fill(tags)
  await page.getByRole('button', { name: '기록 저장', exact: true }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
}

test('name-only CRUD, rating and photo survive refresh; search and stats reflect changes', async ({ page }) => {
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  await start(page)
  await create(page, '우전 녹차')
  await page.reload()
  await expect(page.getByRole('heading', { name: '우전 녹차', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '기록 수정', exact: true }).click()
  await page.getByLabel('차 종류', { exact: true }).selectOption('녹차')
  await page.getByLabel('차 사용량', { exact: true }).fill('4')
  await page.getByRole('button', { name: '5점', exact: true }).click()
  await page.getByLabel('차를 마시면서 느낀 점').fill('아침 공기가 차가워지면서 녹차 향이 더 선명하게 느껴졌다.')
  await page.getByLabel('태그', { exact: true }).fill('아침, 산뜻함')
  await page.locator('input[type=file]').setInputFiles('public/icons/icon-192.png')
  await expect(page.locator('.photo-grid img')).toHaveCount(1)
  await page.getByRole('button', { name: '수정 저장', exact: true }).click()
  await expect(page.getByLabel('5점 중 5점')).toBeVisible()
  await page.reload()
  await expect(page.locator('.detail-photos img')).toHaveCount(1)
  await page.getByRole('navigation').getByRole('link', { name: '기록', exact: true }).click()
  await page.getByLabel('차 이름, 메모, 태그 검색').fill('아침')
  await expect(page.locator('.tea-card')).toHaveCount(1)
  await page.getByLabel('차 이름, 메모, 태그 검색').fill('없는 차')
  await expect(page.locator('.tea-card')).toHaveCount(0)
  await page.getByRole('navigation').getByRole('link', { name: '통계', exact: true }).click()
  await expect(page.locator('.stat-card').nth(0)).toContainText('1 잔')
  await expect(page.locator('.stat-card').nth(1)).toContainText('5.0')
  await expect(page.locator('.bar-row')).toContainText('녹차')
  await page.getByRole('navigation').getByRole('link', { name: '기록', exact: true }).click()
  await page.locator('.tea-card').click()
  await page.getByRole('button', { name: '삭제', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '삭제하기', exact: true }).click()
  await expect(page).toHaveURL(/#\/entries$/)
  await expect(page.locator('.tea-card')).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading', { name: '아직 담긴 이야기가 없어요' })).toBeVisible()
  expect(errors).toEqual([])
})

test('draft resumes after refresh; new draft discards old; saving removes draft', async ({ page }) => {
  await start(page)
  await page.getByRole('navigation').getByRole('link', { name: '새 기록', exact: true }).click()
  await page.getByLabel('차 이름 *').fill('작성 중인 차')
  await page.getByLabel('차 사용량', { exact: true }).fill('3')
  await page.getByLabel('차 사용량', { exact: true }).fill('')
  await page.getByLabel('메모', { exact: true }).fill('초안이 유지되는지 확인')
  await expect(page.getByText('초안 저장됨', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: '이어쓰기', exact: true }).click()
  await expect(page.getByLabel('차 이름 *')).toHaveValue('작성 중인 차')
  await expect(page.getByLabel('메모', { exact: true })).toHaveValue('초안이 유지되는지 확인')
  await page.getByRole('navigation').getByRole('link', { name: '홈', exact: true }).click()
  await page.getByRole('navigation').getByRole('link', { name: '새 기록', exact: true }).click()
  await page.getByRole('button', { name: '새로 작성', exact: true }).click()
  await expect(page.getByLabel('차 이름 *')).toHaveValue('')
  await page.getByLabel('차 이름 *').fill('새로 쓴 차')
  await page.getByRole('button', { name: '기록 저장', exact: true }).click()
  await expect(page.getByRole('heading', { name: '새로 쓴 차', exact: true })).toBeVisible()
  await page.getByRole('navigation').getByRole('link', { name: '새 기록', exact: true }).click()
  await expect(page.getByLabel('차 이름 *')).toHaveValue('')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('JSON export and confirmed replace restore records; invalid file preserves data', async ({ page }) => {
  await start(page)
  await create(page, '백업할 홍차', { category: '홍차', rating: 4 })
  await page.getByRole('navigation').getByRole('link', { name: '설정', exact: true }).click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: '전체 데이터 내보내기' }).click()
  const download = await downloadPromise
  const data = JSON.parse(readFileSync(await download.path(), 'utf8'))
  expect(data.data.entries).toHaveLength(1)
  await page.getByRole('navigation').getByRole('link', { name: '홈', exact: true }).click()
  await create(page, '교체할 녹차', { category: '녹차' })
  await page.getByRole('navigation').getByRole('link', { name: '설정', exact: true }).click()
  await page.locator('#backup-file').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(data)) })
  await page.getByRole('dialog').getByRole('radio', { name: /^전체 교체/ }).check()
  await page.getByRole('button', { name: '전체 교체하기', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const invalid = structuredClone(data)
  invalid.data.entries[0].experience.rating = 99
  await page.locator('#backup-file').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(invalid)) })
  await expect(page.getByText(/백업을 읽을 수 없습니다/)).toBeVisible()
  await page.getByRole('navigation').getByRole('link', { name: '기록', exact: true }).click()
  await expect(page.locator('.tea-card')).toHaveCount(1)
  await expect(page.locator('.tea-card')).toContainText('백업할 홍차')
})

test('custom categories, tools and materials persist; rename does not alter historical records', async ({ page }) => {
  await start(page)
  await page.getByRole('navigation').getByRole('link', { name: '설정', exact: true }).click()
  for (const [store, label, name] of [['categories', '차 종류', '말차'], ['tools', '도구', '여행용 개완'], ['materials', '재질', '스테인리스']]) {
    const manager = page.locator('.option-manager').filter({ has: page.locator(`#option-${store}`) })
    await manager.locator('summary').click()
    await page.getByLabel(`${label} 추가할 이름`, { exact: true }).fill(name)
    await manager.getByRole('button', { name: '추가', exact: true }).click()
    await expect(manager.locator('.option-list')).toContainText(name)
  }
  await page.reload()
  await page.getByRole('navigation').getByRole('link', { name: '새 기록', exact: true }).click()
  await page.getByLabel('차 이름 *').fill('나의 말차')
  await page.getByLabel('차 종류', { exact: true }).selectOption('말차')
  await page.getByLabel('도구', { exact: true }).selectOption('여행용 개완')
  await page.getByLabel('재질', { exact: true }).selectOption('스테인리스')
  await page.getByRole('button', { name: '기록 저장', exact: true }).click()
  await expect(page.locator('.detail-paper')).toContainText('스테인리스')
  await page.getByRole('navigation').getByRole('link', { name: '설정', exact: true }).click()
  const manager = page.locator('.option-manager').first()
  await manager.locator('summary').click()
  await page.getByRole('button', { name: '말차 이름 수정', exact: true }).click()
  await page.getByLabel('차 종류 수정할 이름', { exact: true }).fill('일본 말차')
  await manager.getByRole('button', { name: '수정', exact: true }).click()
  await page.getByRole('navigation').getByRole('link', { name: '기록', exact: true }).click()
  await expect(page.locator('.tea-card')).toContainText('말차')
  await page.locator('.tea-card').click()
  await page.getByRole('link', { name: '기록 수정', exact: true }).click()
  await expect(page.getByLabel('차 종류', { exact: true })).toHaveValue('말차')
})

test('subpath manifest, icon and service worker work; saved records and unvisited routes work offline', async ({ page, context, request }) => {
  const failures = []
  page.on('response', (response) => { if (response.status() >= 400) failures.push(response.url()) })
  await start(page)
  const manifestResponse = await request.get('./manifest.webmanifest')
  expect(manifestResponse.status()).toBe(200)
  const manifest = await manifestResponse.json()
  expect(manifest.start_url).toBe(testBase)
  expect(manifest.scope).toBe(testBase)
  for (const icon of manifest.icons) expect((await request.get(icon.src)).status()).toBe(200)
  await create(page, '오프라인 차', { category: '백차', rating: 3 })
  await page.evaluate(async () => {
    await navigator.serviceWorker.ready
  })
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('heading', { name: '오프라인 차', exact: true })).toBeVisible()
  await expect(page.getByText(/오프라인 ·/)).toBeVisible()
  await page.getByRole('navigation').getByRole('link', { name: '통계', exact: true }).click()
  await expect(page.locator('.stat-card').first()).toContainText('1 잔')
  await page.getByRole('navigation').getByRole('link', { name: '홈', exact: true }).click()
  await create(page, '오프라인에서 새 기록')
  await page.reload()
  await expect(page.getByRole('heading', { name: '오프라인에서 새 기록', exact: true })).toBeVisible()
  expect(failures).toEqual([])
})

test('360/390/430px screens have no horizontal overflow; production is empty and has no samples', async ({ page }) => {
  await start(page)
  await expect(page.locator('.tea-card')).toHaveCount(0)
  await page.screenshot({ path: 'test-results/home-empty-390.png', fullPage: true })
  await create(page, '운남 보이차', { category: '보이차', rating: 4, feeling: '비가 오는 저녁. 평소보다 부드럽고 편안했다.' })
  await create(page, '우전 녹차', { category: '녹차', rating: 5, feeling: '아침 공기가 차가워지면서 녹차 향이 더 선명하게 느껴졌다.' })
  await page.getByRole('navigation').getByRole('link', { name: '홈', exact: true }).click()
  await page.getByRole('button', { name: '알림 닫기', exact: true }).click()
  await page.screenshot({ path: 'test-results/home-mobile-390.png' })
  for (const width of [360, 390, 430, 768, 1280]) {
    await page.setViewportSize({ width, height: 844 })
    for (const route of ['', '#/entries/new', '#/stats', '#/settings']) {
      await page.goto(`./${route}`)
      await expect(page.locator('.page-title, .home-hero')).toBeVisible()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    }
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('./#/entries/new')
  await page.screenshot({ path: 'test-results/form-mobile-390.png', fullPage: true })
  await page.goto('./#/settings')
  await expect(page.getByRole('button', { name: '샘플 기록 3개 추가' })).toHaveCount(0)
})

test('story context, new brewing fields and favorites persist across page closure, editing and JSON restore', async ({ page, context, browser }) => {
  await start(page)
  await page.getByRole('navigation').getByRole('link', { name: '새 기록', exact: true }).click()
  await page.getByLabel('차 이름 *').fill('친구와 마신 청차')
  await page.getByLabel('물 온도', { exact: true }).fill('85.5')
  await page.getByLabel('우림 시간', { exact: true }).fill('60')
  await page.getByLabel('장소 · Where').fill('햇살 드는 창가')
  await page.getByLabel('함께한 사람 · Who').fill('오랜 친구')
  await page.getByLabel('오늘 이 차를 마신 이유 · Why').fill('서로의 이야기를 천천히 듣고 싶어서')
  await page.getByLabel('차를 마시면서 느낀 점').fill('대화가 이어지면서 한 잔의 차가 더 따뜻하게 느껴졌다.')
  await page.getByRole('checkbox', { name: /즐겨찾기에 담기/ }).check()
  await page.getByRole('button', { name: '기록 저장', exact: true }).click()
  await expect(page.getByRole('heading', { name: '친구와 마신 청차' })).toBeVisible()
  const detailURL = page.url()
  await page.close()
  page = await context.newPage()
  await page.goto(detailURL)
  await expect(page.locator('.detail-brew')).toContainText('85.5 °C')
  await expect(page.locator('.detail-brew')).toContainText('60 초')
  await expect(page.locator('.detail-context')).toContainText('햇살 드는 창가')
  await expect(page.locator('.detail-context')).toContainText('오랜 친구')
  await expect(page.locator('.detail-context')).toContainText('서로의 이야기를 천천히 듣고 싶어서')
  await expect(page.getByRole('button', { name: '즐겨찾기 해제', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('link', { name: '기록 수정', exact: true }).click()
  await expect(page.getByLabel('물 온도', { exact: true })).toHaveValue('85.5')
  await expect(page.getByLabel('우림 시간', { exact: true })).toHaveValue('60')
  await page.getByLabel('물 온도', { exact: true }).fill('')
  await page.getByLabel('우림 시간', { exact: true }).fill('0')
  await page.getByRole('button', { name: '수정 저장', exact: true }).click()
  await expect(page.locator('.detail-brew')).toContainText('0 초')
  await page.getByRole('button', { name: '즐겨찾기 해제', exact: true }).click()
  await expect(page.getByRole('button', { name: '즐겨찾기에 담기', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('navigation').getByRole('link', { name: '기록', exact: true }).click()
  await page.getByRole('checkbox', { name: '즐겨찾기만 보기' }).check()
  await expect(page.locator('.tea-card')).toHaveCount(0)
  await page.getByRole('checkbox', { name: '즐겨찾기만 보기' }).uncheck()
  await page.locator('.tea-card').click()
  await page.getByRole('button', { name: '즐겨찾기에 담기', exact: true }).click()
  await expect(page.getByRole('button', { name: '즐겨찾기 해제', exact: true })).toBeVisible()
  await page.getByRole('navigation').getByRole('link', { name: '설정', exact: true }).click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: '전체 데이터 내보내기' }).click()
  const data = JSON.parse(readFileSync(await (await downloadPromise).path(), 'utf8'))
  expect(data.data.entries[0].favorite).toBe(true)
  expect(data.data.entries[0].brewing.waterTemperature).toBeNull()
  expect(data.data.entries[0].brewing.steepTime).toBe(0)
  // Restore on a fresh browser context, which has no existing IndexedDB data.
  const restoredContext = await browser.newContext({ viewport: { width: 390, height: 844 }, locale: 'ko-KR', timezoneId: 'Asia/Seoul' })
  try {
    const restoredPage = await restoredContext.newPage()
    await restoredPage.goto(new URL(`./#/settings`, detailURL).href)
    await restoredPage.locator('#backup-file').setInputFiles({ name: 'story.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(data)) })
    await restoredPage.getByRole('dialog').getByRole('radio', { name: /^전체 교체/ }).check()
    await restoredPage.getByRole('button', { name: '전체 교체하기', exact: true }).click()
    await expect(restoredPage.getByRole('dialog')).toHaveCount(0)
    await restoredPage.getByRole('navigation').getByRole('link', { name: '기록', exact: true }).click()
    await restoredPage.getByRole('checkbox', { name: '즐겨찾기만 보기' }).check()
    await expect(restoredPage.locator('.tea-card')).toHaveCount(1)
    await expect(restoredPage.locator('.tea-card')).toContainText('즐겨찾기')
    await restoredPage.locator('.tea-card').click()
    await expect(restoredPage.locator('.detail-context')).toContainText('서로의 이야기를 천천히 듣고 싶어서')
    await expect(restoredPage.locator('.detail-brew')).toContainText('0 초')
  } finally { await restoredContext.close() }
})

test('old IndexedDB record and draft remain readable and editable after additive model changes', async ({ page }) => {
  await start(page)
  const legacy = createEntry()
  legacy.tea.name = '예전에 남긴 차'
  delete legacy.brewing.waterTemperature
  delete legacy.brewing.steepTime
  delete legacy.favorite
  const draft = structuredClone(legacy)
  draft.id = 'old-draft'
  draft.tea.name = '예전 초안'
  await page.evaluate(async ({ legacy, draft }) => {
    await new Promise((resolve, reject) => {
      const request = indexedDB.open('tea-life-story', 1)
      request.onerror = () => reject(request.error)
      request.onsuccess = () => {
        const db = request.result
        const transaction = db.transaction(['entries', 'settings'], 'readwrite')
        transaction.objectStore('entries').put(legacy)
        transaction.objectStore('settings').put({ key: 'draft', value: draft })
        transaction.oncomplete = () => { db.close(); resolve() }
        transaction.onerror = () => { db.close(); reject(transaction.error) }
      }
    })
  }, { legacy, draft })
  await page.reload()
  await page.locator('.tea-card').click()
  await expect(page.getByRole('heading', { name: '예전에 남긴 차' })).toBeVisible()
  await expect(page.getByRole('button', { name: '즐겨찾기에 담기', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '기록 수정', exact: true }).click()
  await expect(page.getByLabel('물 온도', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('우림 시간', { exact: true })).toHaveValue('')
  await page.getByLabel('물 온도', { exact: true }).fill('90')
  await page.getByRole('button', { name: '수정 저장', exact: true }).click()
  await expect(page.locator('.detail-brew')).toContainText('90 °C')
  await page.getByRole('navigation').getByRole('link', { name: '새 기록', exact: true }).click()
  await page.getByRole('button', { name: '이어쓰기', exact: true }).click()
  await expect(page.getByLabel('차 이름 *')).toHaveValue('예전 초안')
  await expect(page.getByLabel('우림 시간', { exact: true })).toHaveValue('')
  await page.getByLabel('우림 시간', { exact: true }).fill('30')
  await page.getByRole('button', { name: '기록 저장', exact: true }).click()
  await expect(page.getByRole('heading', { name: '예전 초안' })).toBeVisible()
  await expect(page.locator('.detail-brew')).toContainText('30 초')
})
