import { test, expect } from '@playwright/test'

async function start(page) {
  await page.goto(process.env.AUDIT_DEV_URL || './')
  await expect(page.getByRole('heading', { name: '오늘은 어떤 차를 마셨나요?' })).toBeVisible()
}
async function nav(page, name) {
  await page.getByRole('navigation').getByRole('link', { name, exact: true }).click()
}
async function create(page, name, rating = 0) {
  await nav(page, '새 기록')
  await page.getByLabel('차 이름 *').fill(name)
  if (rating) await page.getByRole('button', { name: `${rating}점`, exact: true }).click()
  await page.getByRole('button', { name: '기록 저장', exact: true }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
}

test('tag draft survives reload without blur; typing commas and Enter save preserve distinct tags', async ({ page }) => {
  await start(page)
  await nav(page, '새 기록')
  await page.getByLabel('차 이름 *').fill('태그 초안 검수')
  const tags = page.getByLabel('태그', { exact: true })
  await tags.fill('새벽, ')
  await expect(tags).toHaveValue('새벽, ')
  await tags.pressSequentially('자사호')
  await expect(page.getByText('초안 저장됨', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: '이어쓰기', exact: true }).click()
  await expect(tags).toHaveValue('새벽, 자사호')
  await tags.press('End')
  await tags.pressSequentially(', 편안함')
  await tags.press('Enter')
  await expect(page.getByRole('heading', { name: '태그 초안 검수', exact: true })).toBeVisible()
  await expect(page.locator('.detail-paper .tag-row span')).toHaveText(['#새벽', '#자사호', '#편안함'])
  await page.reload()
  await expect(page.locator('.detail-paper .tag-row span')).toHaveCount(3)
  await nav(page, '기록')
  await page.getByLabel('차 이름, 메모, 태그 검색').fill('편안함')
  await expect(page.locator('.tea-card')).toHaveCount(1)
  await page.locator('.tea-card').click()
  await page.getByRole('link', { name: '기록 수정', exact: true }).click()
  const prefix = '차'.repeat(100)
  await tags.fill(`${prefix}A, ${prefix}B, # 아침, 아침`)
  await page.getByRole('button', { name: '수정 저장', exact: true }).click()
  await expect(page.locator('.detail-paper .tag-row span')).toHaveText([`#${prefix}`, '#아침'])
})

test('empty month does not count every record; missing rating and period filters describe their scope', async ({ page }) => {
  await start(page)
  await create(page, '이번 달 평점', 5)
  await create(page, '이번 달 미입력')
  await create(page, '지난달 평점', 3)
  await page.getByRole('link', { name: '기록 수정', exact: true }).click()
  const date = await page.getByLabel('날짜 · When').inputValue()
  const [year, month] = date.split('-').map(Number)
  const previous = `${month === 1 ? year - 1 : year}-${String(month === 1 ? 12 : month - 1).padStart(2, '0')}-01`
  await page.getByLabel('날짜 · When').fill(previous)
  await page.getByRole('button', { name: '수정 저장', exact: true }).click()
  await nav(page, '통계')
  await expect(page.locator('.stat-card').nth(0)).toContainText('2 잔')
  await expect(page.locator('.stat-card').nth(1)).toContainText('5.0')
  await page.getByLabel('돌아보고 싶은 달').fill('')
  await expect(page.getByRole('heading', { name: '돌아볼 달을 선택해 주세요' })).toBeVisible()
  await expect(page.locator('.stat-card').nth(0)).toContainText('0 잔')
  await expect(page.locator('.stat-card').nth(1)).toContainText('—')
  await page.getByLabel('돌아보고 싶은 달').fill(date.slice(0, 7))
  await expect(page.locator('.stat-card').nth(0)).toContainText('2 잔')
  await expect(page.locator('.stat-card').nth(1)).toContainText('5.0')
  await nav(page, '기록')
  await page.locator('.filter-panel summary').click()
  await page.getByLabel('평점', { exact: true }).selectOption('0')
  await expect(page.locator('.filter-panel summary')).toContainText('평점 미입력')
  await expect(page.locator('.tea-card')).toHaveCount(1)
  await page.getByLabel('시작일', { exact: true }).fill(date)
  await page.locator('.filter-panel summary').click()
  await expect(page.locator('.filter-panel summary')).toContainText('기간 적용')
  await page.locator('.filter-panel summary').click()
  await page.getByRole('button', { name: '필터 초기화', exact: true }).click()
  await expect(page.locator('.tea-card')).toHaveCount(3)
})

test('a draft left after cleanup failure cannot overwrite an already edited saved record', async ({ page }) => {
  await start(page)
  await nav(page, '새 기록')
  await page.getByLabel('차 이름 *').fill('초안 정리 실패 검수')
  await page.getByLabel('메모', { exact: true }).fill('처음 메모')
  await expect(page.getByText('초안 저장됨', { exact: true })).toBeVisible()
  await page.evaluate(() => {
    const original = IDBObjectStore.prototype.delete
    IDBObjectStore.prototype.delete = function (key) {
      if (this.name === 'settings' && key === 'draft') {
        IDBObjectStore.prototype.delete = original
        throw new DOMException('Draft cleanup failed', 'QuotaExceededError')
      }
      return original.call(this, key)
    }
  })
  await page.getByRole('button', { name: '기록 저장', exact: true }).click()
  await expect(page.getByRole('heading', { name: '초안 정리 실패 검수' })).toBeVisible()
  const originalURL = page.url()
  await expect(page.getByRole('alert')).toContainText('기록은 저장됐지만')
  await page.getByRole('link', { name: '기록 수정', exact: true }).click()
  await page.getByLabel('메모', { exact: true }).fill('최종 수정한 메모')
  await page.getByRole('button', { name: '수정 저장', exact: true }).click()
  await expect(page.locator('.detail-paper')).toContainText('최종 수정한 메모')
  await nav(page, '새 기록')
  await page.getByRole('button', { name: '이어쓰기', exact: true }).click()
  await expect(page.getByText(/초안은 새 기록으로 이어갈게요/)).toBeVisible()
  await expect(page.getByLabel('메모', { exact: true })).toHaveValue('처음 메모')
  await page.getByRole('button', { name: '기록 저장', exact: true }).click()
  await expect(page.getByRole('heading', { name: '초안 정리 실패 검수' })).toBeVisible()
  expect(page.url()).not.toBe(originalURL)
  await nav(page, '기록')
  await expect(page.locator('.tea-card')).toHaveCount(2)
  await page.goto(originalURL)
  await expect(page.locator('.detail-paper')).toContainText('최종 수정한 메모')
  await page.reload()
  await expect(page.locator('.detail-paper')).toContainText('최종 수정한 메모')
})

test('whitespace name points to the field instead of reporting a storage failure', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 640 })
  await start(page)
  await nav(page, '새 기록')
  const input = page.getByLabel('차 이름 *')
  await input.fill('   ')
  await page.getByRole('button', { name: '기록 저장', exact: true }).click()
  await expect(input).toBeFocused()
  expect(await input.evaluate((field) => field.validationMessage)).toBe('차 이름을 한 글자 이상 적어 주세요.')
  await expect(page.getByRole('alert')).toHaveCount(0)
  await input.fill('필수 입력 검수')
  await page.getByRole('button', { name: '기록 저장', exact: true }).click()
  await expect(page.getByRole('heading', { name: '필수 입력 검수', exact: true })).toBeVisible()
  await nav(page, '기록')
  await expect(page.locator('.tea-card')).toHaveCount(1)
  await nav(page, '새 기록')
  await expect(input).toBeVisible()
  const layout = await input.evaluate((field) => ({ bottom: field.getBoundingClientRect().bottom, saveTop: document.querySelector('.save-bar').getBoundingClientRect().top }))
  expect(layout.bottom).toBeLessThanOrEqual(layout.saveTop)
})
